Update pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -2,27 +2,40 @@
 
 MINIMAL_VERSION="1.3.0"
 
-# Check ktlint version
-KT_VERSION=$(ktlint -v | awk '{print $3}')
+check_ktlint_version() {
+    if ! command -v ktlint &> /dev/null; then
+        echo "Error: ktlint is not installed. Please install it with 'brew install ktlint'."
+        exit 1
+    fi
 
-# Compare versions
-if [[ "$(printf '%s\n' "$MINIMAL_VERSION" "$KT_VERSION" | sort -V | head -n1)" != "$MINIMAL_VERSION" ]]; then
-    echo "Warning: Your ktlint version ($KT_VERSION) is lower than the minimal required version ($MINIMAL_VERSION). Upgrading..."
-    brew upgrade ktlint
-elif [[ "$KT_VERSION" > "$MINIMAL_VERSION" ]]; then
-    echo -e "\e[33mWarning: Your ktlint version ($KT_VERSION) is higher than the minimal required version ($MINIMAL_VERSION)."
-    echo "This could result in different behavior. Consider upgrading the minimal version."
-fi
+    KT_VERSION=$(ktlint -v | awk '{print $3}')
 
-echo "ktlint version: $KT_VERSION"
+    # Compare versions
+    if [[ "$(printf '%s\n' "$MINIMAL_VERSION" "$KT_VERSION" | sort -V | head -n1)" != "$MINIMAL_VERSION" ]]; then
+        echo "Warning: Your ktlint version ($KT_VERSION) is lower than the minimal required version ($MINIMAL_VERSION). Upgrading..."
+        brew upgrade ktlint
+    elif [[ "$KT_VERSION" > "$MINIMAL_VERSION" ]]; then
+        echo -e "\e[33mWarning: Your ktlint version ($KT_VERSION) is higher than the minimal required version ($MINIMAL_VERSION)."
+        echo "This could result in different behavior. Consider upgrading the minimal version."
+    fi
 
-echo "Pre commit: Formats the code with ktlint (install with brew install ktlint) ..."
-echo ""
-ktlint -F "*/src/**/*.kt"
+    echo "ktlint version: $KT_VERSION"
+}
 
-KT_EXIT_CODE=$?
+run_ktlint() {
+    echo "Running ktlint to check code formatting..."
+    ktlint_output=$(ktlint -F "*/src/**/*.kt" 2>&1)
+    KT_EXIT_CODE=$?
 
-if [ $KT_EXIT_CODE -ne 0 ]; then
-    echo "Error: 'ktlint -F \"*/src/**/*.kt\"' failed. Please fix the issues before committing."
-    exit 1
-fi
+    if [ $KT_EXIT_CODE -ne 0 ]; then
+        echo -e "\e[33mWarning: 'ktlint -F \"*/src/**/*.kt\"' found formatting issues."
+        echo "$ktlint_output"  # Print ktlint output for debugging
+    else
+        echo "No formatting issues found."
+    fi
+}
+
+check_ktlint_version
+run_ktlint
+
+echo "Pre-commit checks completed."
